name: Publish

on:
    push:
        branches:
            - "main"

env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Publish
        steps:
            - uses: actions/checkout@v3

            - uses: oven-sh/setup-bun@v1

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: "https://registry.npmjs.org"

            - run: |
                  bun install
                  bun run build

            - run: npm publish --access public
